version: '3.8'

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    hostname: dynamodb
    volumes:
      - dynamodb-data:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
    networks:
      - sam-local

volumes:
  dynamodb-data: {}

networks:
  sam-local:
    name: sam-local-net
