AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  swimming-results-api

  SAM Template for swimming-results-api
  
Parameters:
  ServiceName:
    Type: String
    Default: swimming-api
  StageName:
    Description: The name of the deployment stage dev, prod, or local
    Type: String
    AllowedValues:
      - dev
      - prod
      - local
    Default: local

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs14.x
    MemorySize: 256
    ReservedConcurrentExecutions: 5
    Tracing: Active
    Tags:
      'greenhorn:project': 'Swimming Results API'
      'greenhorn:service-name': !Sub "${ServiceName}"
      'greenhorn:owner': 'Rigikulm'
    Environment:
      Variables:
        TABLE_NAME: !Sub "swimming-results-db-${StageName}"
        STAGE: !Ref StageName

Resources:
  EventResultsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "${ServiceName}-${StageName}-get-event-results"
      Description: 'Returns the swimmers results for a particular event'
      CodeUri: src/functions
      Handler: get-event-results.handler
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        SwimResultsQuery:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /swimming/results/{eventId}
            Method: get
  EventPersonalRecordFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "${ServiceName}-${StageName}-get-event-pr"
      Description: 'Returns the swimmers personal record for a particular event'
      CodeUri: src/functions
      Handler: get-event-pr.handler
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        SwimResultsQuery:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /swimming/results/{eventId}/pr
            Method: get
  CreateEventResultFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "${ServiceName}-${StageName}-post-event-result"
      Description: 'Creates a new swimming result entry'
      CodeUri: src/functions
      Handler: post-event-result.handler
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        Create:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /swimming/results
            Method: post
  SwimmingResultsDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "pk"
          AttributeType: "S"
        -
          AttributeName: "sk"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "pk"
          KeyType: "HASH"
        -
          AttributeName: "sk"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: !Sub "swimming-results-db-${StageName}"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SwimResultsApi:
    Description: "API Gateway endpoint URL for Prod stage for the results function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/swimming"
